#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"; cd "$ROOT"
PY="${PYTHON_BIN:-python3}"
bash -n self-improvement/run_daily_improvement.sh scripts/install_self_improvement_macos.sh scripts/set_promotion_mode.sh scripts/controller_status.sh scripts/preflight_macos.sh
command -v zsh >/dev/null 2>&1 && zsh -n self-improvement/run_daily_improvement.sh || true
"$PY" -m py_compile scripts/baseline_validate.py scripts/agent_phase_guard.py scripts/triage_plan.py scripts/triage_output.py scripts/triage_infer.py scripts/fresh_probe.py scripts/ollama_model_check.py scripts/run_with_deadline.py scripts/candidate_gate.py scripts/cleanup_worktrees.py tests/test_controller_v2.py
run_group(){ "$PY" -m unittest -v "$@"; }
run_group tests.test_controller_v2.T.test_01_nochange tests.test_controller_v2.T.test_02_default_no_promote tests.test_controller_v2.T.test_03_skills_promote
run_group tests.test_controller_v2.T.test_04_core_promote tests.test_controller_v2.T.test_05_sensitive_block tests.test_controller_v2.T.test_06_syntax_block
run_group tests.test_controller_v2.T.test_07_test_tamper_block tests.test_controller_v2.T.test_08_dep_block tests.test_controller_v2.T.test_09_rollback
run_group tests.test_controller_v2.T.test_10_baseline_move tests.test_controller_v2.T.test_11_dirty tests.test_controller_v2.T.test_12_bad_mode tests.test_controller_v2.T.test_13_bad_manifest
run_group tests.test_controller_v2.T.test_14_deadline tests.test_controller_v2.T.test_15_cleanup
run_group tests.test_controller_v2.T.test_16_runner_end_to_end_isolated
run_group tests.test_controller_v2.T.test_17_runner_watchdog
run_group tests.test_controller_v2.T.test_18_runner_has_gate_and_deadline tests.test_controller_v2.T.test_19_agent_cannot_direct_deploy tests.test_controller_v2.T.test_20_default_policy_off
run_group tests.test_controller_v2.T.test_21_env_overrides_policy
run_group tests.test_controller_v2.T.test_22_deadline_forwards_term tests.test_controller_v2.T.test_23_deadline_forwards_int tests.test_controller_v2.T.test_24_master_prompt_not_injected_wholesale tests.test_controller_v2.T.test_25_context_enforces_anti_recursion_and_budget
run_group tests.test_controller_v2.T.test_26_baseline_validation_outside_agent tests.test_controller_v2.T.test_27_no_precandidate_full_tests tests.test_controller_v2.T.test_28_baseline_cache tests.test_controller_v2.T.test_29_candidate_gate_prefers_worktree_dev_python
run_group tests.test_controller_v2.T.test_30_baseline_sync_without_lock tests.test_controller_v2.T.test_31_agent_phase_guard_restores tests.test_controller_v2.T.test_32_failed_baseline_not_cached
run_group tests.test_controller_v2.T.test_33_uv_common_path_discovery tests.test_controller_v2.T.test_34_agent_guard_blocks_broad_pytest_and_uv_sync tests.test_controller_v2.T.test_35_context_rejects_history_and_todo_hunting tests.test_controller_v2.T.test_36_runner_uses_path_guard
run_group tests.test_controller_v2.T.test_37_runner_skips_agent_if_environment_unready tests.test_controller_v2.T.test_38_uv_sibling_of_hermes_python tests.test_controller_v2.T.test_39_uv_home_hermes_discovery
run_group tests.test_controller_v2.T.test_40_runner_skips_agent_on_failed_baseline tests.test_controller_v2.T.test_41_deadline_forwards_hup tests.test_controller_v2.T.test_42_runner_tracks_watchdog_and_hup tests.test_controller_v2.T.test_43_runner_has_orphan_agent_gate
run_group tests.test_controller_v2.T.test_44_baseline_uses_all_plus_dev_when_available
run_group tests.test_controller_v2.T.test_45_baseline_validator_without_tomllib
run_group tests.test_controller_v2.T.test_46_baseline_classifies_and_caches_known_red
run_group tests.test_controller_v2.T.test_47_runner_allows_known_red_research_only_when_off
run_group tests.test_controller_v2.T.test_48_runner_blocks_known_red_when_promotion_enabled
run_group tests.test_controller_v2.T.test_49_candidate_gate_uses_wrapper_and_accepts_nonworse_red tests.test_controller_v2.T.test_50_candidate_gate_rejects_worse_red

run_group tests.test_controller_v2.T.test_51_agent_guard_blocks_directory_pytest_targets tests.test_controller_v2.T.test_52_context_requires_file_or_node_target
run_group tests.test_controller_v2.T.test_53_runner_sets_known_red_flag_before_task tests.test_controller_v2.T.test_54_context_treats_red_failures_as_evidence_not_backlog
run_group tests.test_controller_v2.T.test_55_triage_plan_validator_accepts_safe_and_rejects_bad tests.test_controller_v2.T.test_56_runner_uses_qwen_then_gemma_with_split_budget
run_group tests.test_controller_v2.T.test_57_triage_source_edit_aborts_before_gemma tests.test_controller_v2.T.test_58_triage_no_change_skips_implementation tests.test_controller_v2.T.test_59_runner_reports_both_stage_models
run_group tests.test_controller_v2.T.test_60_triage_guard_blocks_all_pytest_and_broad_inventory tests.test_controller_v2.T.test_61_runner_pins_models_and_minimal_triage_reasoning tests.test_controller_v2.T.test_62_triage_contract_forces_early_plan_without_tests
run_group tests.test_controller_v2.T.test_63_installer_safely_migrates_only_old_triage_defaults tests.test_controller_v2.T.test_64_preflight_reports_model_and_reasoning_override_support
run_group tests.test_controller_v2.T.test_65_discovery_model_is_qwen35_mlx tests.test_controller_v2.T.test_66_installer_migrates_only_exact_old_discovery_model tests.test_controller_v2.T.test_67_ollama_context_checker_rejects_sub64k tests.test_controller_v2.T.test_68_preflight_enforces_context_and_pull_hint
run_group tests.test_controller_v2.T.test_69_triage_output_materializes_valid_json tests.test_controller_v2.T.test_70_triage_output_safe_nochange_fallback_only
run_group tests.test_controller_v2.T.test_71_runner_accepts_nochange_from_transcript tests.test_controller_v2.T.test_72_runner_accepts_structured_transcript_and_starts_gemma
run_group tests.test_controller_v2.T.test_73_fresh_probe_selects_safe_failure_and_blocks_risky tests.test_controller_v2.T.test_74_fresh_probe_rotates_across_safe_failures
run_group tests.test_controller_v2.T.test_75_runner_passes_fresh_probe_to_triage tests.test_controller_v2.T.test_76_installer_preflight_and_policy_include_fresh_probe
run_group tests.test_controller_v2.T.test_77_fresh_probe_includes_test_and_source_context tests.test_controller_v2.T.test_78_context_packet_is_bounded_and_production_only
run_group tests.test_controller_v2.T.test_79_runner_uses_probe_context_before_more_discovery tests.test_controller_v2.T.test_80_fresh_probe_python39_compatible
run_group tests.test_controller_v2.T.test_81_triage_infer_uses_schema_no_tools_and_think_false tests.test_controller_v2.T.test_82_triage_infer_rejects_nonlocal_endpoint
run_group tests.test_controller_v2.T.test_83_runner_direct_triage_has_no_hermes_tools tests.test_controller_v2.T.test_84_guard_is_installed_only_after_valid_implement
run_group tests.test_controller_v2.T.test_85_direct_nochange_skips_gemma_cleanly tests.test_controller_v2.T.test_86_direct_implement_starts_gemma
run_group tests.test_controller_v2.T.test_87_implement_plan_is_bound_to_fresh_probe_evidence
run_group tests.test_controller_v2.T.test_88_probe_skips_missing_dependency_and_selects_next_failure tests.test_controller_v2.T.test_89_probe_skips_resolved_pass_and_selects_next_failure
run_group tests.test_controller_v2.T.test_90_probe_attempt_budget_is_bounded_and_cursor_advances tests.test_controller_v2.T.test_91_policy_runner_installer_preflight_include_probe_attempt_cap
run_group tests.test_controller_v2.T.test_92_probe_timeout_is_shared_across_attempts tests.test_controller_v2.T.test_93_no_actionable_probe_cannot_authorize_implement
run_group tests.test_controller_v2.T.test_94_probe_focuses_on_assertion_terms_deep_in_production_definition tests.test_controller_v2.T.test_95_runner_classifier_sees_only_selected_probe_candidate
run_group tests.test_controller_v2.T.test_96_multiline_definition_fallback_includes_function_body tests.test_controller_v2.T.test_97_patch_target_helper_is_included_as_production_evidence
run_group tests.test_controller_v2.T.test_98_failure_proximity_prioritizes_behavior_under_test
run_group tests.test_controller_v2.T.test_99_primary_function_expands_direct_production_helpers
run_group tests.test_controller_v2.T.test_100_probe_skips_explicit_dependency_warning_and_selects_next_failure
run_group tests.test_controller_v2.T.test_101_focused_terms_prefer_executable_assignments_over_prose tests.test_controller_v2.T.test_102_context_includes_bounded_local_test_helper
run_group tests.test_controller_v2.T.test_103_patched_direct_helper_outranks_unrelated_guards
run_group tests.test_controller_v2.T.test_104_control_flow_guard_outranks_context_output_assignments
echo 'ALL 104 CONTROLLER TESTS PASS'
